---
title: "Final Project"
author: "Bansara,Gallo,Olivo,Quillo"
date: "2023-12-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Select a website that you want to scrape 300 reviews. 
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

reviews = data.frame()

for(counterrr in 1:12){
  looplink = paste0("https://www.imdb.com/title/tt1517268/reviews?sort=userRating&dir=desc&ratingFilter=", + counterrr)
  
  link = looplink
  
  session <- bow(link,
               user_agent = "For Educational Purpose")

  
  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

      rating_name <- scrapeNodes("span.display-name-link")
 

      rating_title <- scrapeNodes("a.title")
      
      
      rating_contents <- scrapeNodes("div.content")
      
      
      rating_date <- scrapeNodes("span.review-date")
      
      
      rating_ratings <- scrapeNodes("div.ipl-ratings-bar")

      reviews <- rbind(reviews, data.frame(name = rating_name,
                      title = rating_title,
                      contents = rating_contents,
                      date = rating_date,
                      ratings = rating_ratings))

}

```


printing 100 reviews out of 300 because I cant print all 300.
```{r}

reviews[1:100,1:5]

```


```{r}
ratingsszz <- reviews$ratings

ratingzznum <- as.factor(ratingsszz)

ratingzznum2 <- as.numeric(ratingzznum)

ratings_mean <- mean(ratingzznum2)

ratings_mean

value <- ratings_mean

total <- 10

proportion <- value / total

barplot(proportion, names.arg = "Proportion", col = "skyblue", main = "Proportion out of 10", ylab = "Proportion", ylim = c(0, 1))

#As we observe the mean from our ratings is 4.915557. Over all the 300 revies we took we got a 4.9 ratings out of 10 which is low and negative. 

```